version: '3.8'

services:
  notification-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: scholar-notification-service
    env_file:
      - .env
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://service-registry:8761/eureka/
      - NOTIFICATION_DB_PORT=${NOTIFICATION_DB_PORT}
      - NOTIFICATION_DB_USER=${NOTIFICATION_DB_USER}
      - NOTIFICATION_DB_PASSWORD=${NOTIFICATION_DB_PASSWORD}
      - RABBITMQ_HOST=user-rabbitmq
      - RABBITMQ_PORT=${RABBITMQ_PORT}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SPRING_RABBITMQ_HOST=user-rabbitmq
      - SPRING_RABBITMQ_PORT=${RABBITMQ_PORT}
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USER}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - GMAIL_ADDRESS=${GMAIL_ADDRESS}
      - GMAIL_APP_PASSWORD=${GMAIL_APP_PASSWORD}
    networks:
      - scholarai-network
    restart: unless-stopped
    # Will connect to existing infrastructure via network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Note: notification-postgres is already running from meta/Scripts/docker.sh
  # This service will connect to the existing notification-db container

  # Note: rabbitmq is already running from meta/Scripts/docker.sh
  # This service will connect to the existing user-rabbitmq container

  # Note: service-registry is already running from the main orchestration
  # This service will connect to the existing service-registry container

# Volumes are managed by meta/Scripts/docker.sh

networks:
  scholarai-network:
    external: true
    name: docker_scholarai-network
